// The console's speaker.
//
// Loaded through a Loader rather than imported by the panel, and that is the
// whole reason this is a separate file: if QtMultimedia is not present on a
// machine, an import at the top of Panel.qml would fail to compile the panel
// and the widget would not appear at all. A Loader that fails leaves `item`
// null, `play()` is never reached, and everything else still works — silently,
// which is the correct way for sound to be unavailable.
//
// The files themselves are generated by the helper (`micromachee sounds`), so
// nothing here ships audio and the bank can be regenerated on install.

import QtQuick
import QtMultimedia

Item {
  id: root

  /// Directory the helper wrote the bank into.
  property string dir: ""
  /// Kept low on purpose. This lives in a bar, beside whatever else is playing.
  property real level: 0.32

  readonly property var names: [
    "0-blip", "1-hit", "2-boom", "3-pickup", "4-jump", "5-hurt", "6-win", "7-lose"
  ]

  function play(n) {
    if (dir === "") return
    var i = Math.floor(n) % 8
    if (i < 0) i += 8
    var e = bank.itemAt(i)
    if (!e) return
    // Restart rather than ignore: two hits in three frames should be two
    // sounds, not one sound and a dropped one.
    e.stop()
    e.play()
  }

  Repeater {
    id: bank
    model: root.names
    delegate: SoundEffect {
      required property var modelData
      source: root.dir === "" ? "" : "file://" + root.dir + "/" + modelData + ".wav"
      volume: root.level
    }
  }
}
