// Generated by helper/src/palettes.rs — do not edit.
// Regenerate: MICROMACHEE_WRITE_PALETTES=1 cargo test --manifest-path helper/Cargo.toml

export const VERSION = "0.35.0";
export const CATALOG =
  "https://pixygontech.b-cdn.net/releases/micromachee/0.35.0/catalog.json";

export const W = 240;
export const H = 160;
export const CHAR_WIDTH = 4;
export const LINE_HEIGHT = 6;

// slot -> five rows of three bits, most significant bit leftmost
export const FONT = {
  " ": [0,0,0,0,0],
  "A": [2,5,7,5,5],
  "B": [6,5,6,5,6],
  "C": [3,4,4,4,3],
  "D": [6,5,5,5,6],
  "E": [7,4,6,4,7],
  "F": [7,4,6,4,4],
  "G": [3,4,5,5,3],
  "H": [5,5,7,5,5],
  "I": [7,2,2,2,7],
  "J": [1,1,1,5,2],
  "K": [5,5,6,5,5],
  "L": [4,4,4,4,7],
  "M": [5,7,7,5,5],
  "N": [6,5,5,5,5],
  "O": [2,5,5,5,2],
  "P": [6,5,6,4,4],
  "Q": [2,5,5,7,3],
  "R": [6,5,6,5,5],
  "S": [3,4,2,1,6],
  "T": [7,2,2,2,2],
  "U": [5,5,5,5,3],
  "V": [5,5,5,2,2],
  "W": [5,5,7,7,5],
  "X": [5,5,2,5,5],
  "Y": [5,5,2,2,2],
  "Z": [7,1,2,4,7],
  "0": [7,5,5,5,7],
  "1": [2,6,2,2,7],
  "2": [6,1,2,4,7],
  "3": [7,1,3,1,7],
  "4": [5,5,7,1,1],
  "5": [7,4,6,1,6],
  "6": [3,4,6,5,2],
  "7": [7,1,2,2,2],
  "8": [2,5,2,5,2],
  "9": [2,5,3,1,6],
  ".": [0,0,0,0,2],
  ",": [0,0,0,2,4],
  ":": [0,2,0,2,0],
  ";": [0,2,0,2,4],
  "!": [2,2,2,0,2],
  "?": [6,1,2,0,2],
  "-": [0,0,7,0,0],
  "_": [0,0,0,0,7],
  "+": [0,2,7,2,0],
  "=": [0,7,0,7,0],
  "*": [5,2,7,2,5],
  "/": [1,1,2,4,4],
  "\\": [4,4,2,1,1],
  "'": [2,2,0,0,0],
  "\"": [5,5,0,0,0],
  "(": [1,2,2,2,1],
  ")": [4,2,2,2,4],
  "[": [3,2,2,2,3],
  "]": [6,2,2,2,6],
  "<": [1,2,4,2,1],
  ">": [4,2,1,2,4],
  "%": [5,1,2,4,5],
  "#": [5,7,5,7,5],
  "@": [2,5,7,4,3],
  "&": [2,5,2,5,3],
  "^": [2,5,0,0,0],
};

// dark to light; every theme keeps this order
export const RANK = [0, 1, 2, 6, 3, 5, 4, 7];

export const THEMES = {
  "micromachee": ["#000000", "#1d2b53", "#ff004d", "#ffa300", "#ffec27", "#00e436", "#29adff", "#fff1e8"],
  "gameboy": ["#08170a", "#234f25", "#668008", "#5fb75f", "#bcd746", "#87c43d", "#5fa25f", "#c7e34a"],
  "amber": ["#1a0d00", "#693800", "#bd5910", "#f98500", "#ffbf6e", "#fd9c14", "#d57d13", "#ffcf7a"],
  "noir": ["#050505", "#515151", "#8c8c8c", "#c3c3c3", "#f1f1f1", "#d5d5d5", "#aeaeae", "#ffffff"],
  "sweet": ["#1a1226", "#60447f", "#f04c71", "#ffa980", "#ffe8b1", "#85e392", "#73adf1", "#fdf6ee"],
  "abyss": ["#04070d", "#354b78", "#f03d61", "#fba352", "#efe2ab", "#84d8ac", "#65a4ff", "#e6f0f8"],
};

// the screen each theme imitates — display effects, never pixels
export const THEME_FX = {
  "micromachee": { scanline: 0.300, bloom: 0.340, aberration: 0.550, noise: 0.030, vignette: 0.220, grid: 0.000, persist: 0.060 },
  "gameboy": { scanline: 0.000, bloom: 0.000, aberration: 0.000, noise: 0.000, vignette: 0.140, grid: 0.550, persist: 0.340 },
  "amber": { scanline: 0.320, bloom: 0.550, aberration: 0.000, noise: 0.045, vignette: 0.300, grid: 0.000, persist: 0.300 },
  "noir": { scanline: 0.400, bloom: 0.220, aberration: 0.120, noise: 0.110, vignette: 0.340, grid: 0.000, persist: 0.100 },
  "sweet": { scanline: 0.000, bloom: 0.440, aberration: 0.220, noise: 0.015, vignette: 0.140, grid: 0.000, persist: 0.080 },
  "abyss": { scanline: 0.160, bloom: 0.320, aberration: 0.200, noise: 0.040, vignette: 0.440, grid: 0.000, persist: 0.140 },
};
